### ISSUE TITLE
Rename to awesome-azure-functions

### ISSUE THREAD

**Issue by kunjee17** [markheath/azure-functions-links#3]
Hi,

Thanks for wonderful collection of links.

Is it possible to rename is this to `awesome-azure-functions`. It would be inline with awesome list and easier to search via google. As people (at least me) search things with awesome whenever I like to find curated resources.

**Comment by markheath** [comment]
Thanks for the suggestion. I agree that would have been a better name. But one of the reasons for creating this was so that viewers of [my Azure Functions Pluralsight courses](https://app.pluralsight.com/profile/author/mark-heath) can visit this for more information, and the videos contain the link to this address. So I'd prefer not to change the repository name now.
